include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/common/utils/bitcoin_flutter/**
    - "**/*.g.dart"
  strong-mode:
    implicit-casts: false
  errors:
    missing_required_param: error
    parameter_assignments: error
    avoid_relative_lib_imports: error
linter:
  rules:
    - parameter_assignments
    - avoid_relative_lib_imports
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
