name: moviepedia
description: Another Flutter UI challenge project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.3.0
  equatable: ^2.0.3
  retrofit: ^2.0.1
  json_annotation: ^4.1.0
  logger: ^1.1.0
  dio: ^4.0.0
  fluent_assertions: ^0.4.0
  get_it: ^7.2.0
  sliver_tools: ^0.2.5
  debounce_throttle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10
  build_runner: ^2.1.4
  pedantic: ^1.11.1
  json_serializable: ^5.0.2
  retrofit_generator: ^2.0.1+2
  mock_web_server: ^5.0.0-nullsafety.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/

